Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
